# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=800)),
                ('inversion_ejercida', models.DecimalField(decimal_places=2, max_digits=20)),
                ('avance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('beneficiarios_hombres', models.IntegerField(default=0)),
                ('beneficiarios_mujeres', models.IntegerField(default=0)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.Municipio')),
            ],
        ),
    ]
