# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0004_auto_20160112_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipio',
            options={'ordering': ['nombre']},
        ),
    ]
