# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0005_auto_20160112_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='region',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='obra',
            name='dependencia',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
