# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0010_auto_20160120_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='estatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
