# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0011_auto_20160120_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='estatus',
            field=models.CharField(blank=True, choices=[('En Ejecuci\xf3n', 'En Ejecuci\xf3n'), ('Conclu\xedda', 'Conclu\xedda')], max_length=50, null=True),
        ),
    ]
