# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 23:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0013_auto_20160120_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='municipio',
            new_name='municipios',
        ),
    ]
