# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0014_auto_20160120_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='municipios',
            new_name='municipio',
        ),
    ]
