# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0015_auto_20160120_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='municipio',
        ),
        migrations.AddField(
            model_name='obra',
            name='municipios',
            field=models.ManyToManyField(to='obras.Municipio'),
        ),
    ]
