# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0016_auto_20160120_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='municipios',
        ),
        migrations.AddField(
            model_name='obra',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='obras.Municipio'),
            preserve_default=False,
        ),
    ]
